[package]
name = "byeefree_esp32s3_p2p_embassy"
version = "0.1.1"
authors = ["Peter Krull <peterkrullpeter@gmail.com>", "qsbye <2557877116@qq.com>"]
edition = "2021"
license = "Apache-2.0"
description = "基于esp32s3的点对点通信无线串口"

[features]
usb-serial = []
println = []

[dependencies]
# esp32开发相关
esp-hal = { version = "0.23.1", features = ["esp32s3"] }
# 用于操作低功耗riscv核
esp-lp-hal = { version = "0.1.0", features = ["esp32s3", "embedded-io", "debug"] }


# esp-hal = { git = "https://github.com/esp-rs/esp-hal", features = [ "esp32s3" ] }
# esp-println = { git = "https://github.com/esp-rs/esp-hal", features = ["esp32s3", "log"] }
# esp-alloc = { git = "https://github.com/esp-rs/esp-hal" }
# esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal", features = ["esp32s3"] }
# esp-backtrace = { git = "https://github.com/esp-rs/esp-hal", features = [
#     "exception-handler",
#     "panic-handler",
#     "println",
#     "esp32s3",
# ] }
# esp-wifi = { git = "https://github.com/esp-rs/esp-hal", features = [
#     "esp32s3",
#     "esp-now",
#     "async",
#     "phy-enable-usb",
#     "utils",
#     "wifi",
# ] }

# embassy框架相关(配合esp-hal-embassy)
embassy-executor = { version = "0.6.3", features = ["task-arena-size-65536"] }
embassy-futures = { version = "0.1.1" }
embassy-sync = { version = "0.6.1" }
embassy-time-driver = { version = "0.1.0", features = [ "tick-hz-1_000_000" ] }
embassy-time = { version = "0.3.2" }
embedded-io = { version = "0.6.1", features = ["defmt-03"] }

# 静态变量
static_cell = "2.1.0"

# 日志
log = { version = "0.4.22" }

# 网络相关
# smoltcp = { version = "0.12.0", default-features = false, features = [
#     "medium-ethernet",
#     "proto-dhcpv4",
#     "proto-igmp",
#     "proto-ipv4",
#     "socket-dhcpv4",
#     "socket-icmp",
#     "socket-raw",
#     "socket-tcp",
#     "socket-udp",
# ] }

[profile.dev]
opt-level = "s"

[profile.release]
# LLVM可以使用单线程执行更好的优化
codegen-units = 1 
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
